# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

env:
  DATABASE_URL: "postgres://jonathan:pass@localhost:5432/capacitacao"
  NEXTAUTH_SECRET: "dummysecret"
  NEXTAUTH_URL: "http://localhost:3000"
  GITHUB_CLIENT_ID: 123
  GITHUB_CLIENT_SECRET: 123

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --prefer-offline
      - name: Linting all files
        run: SKIP_ENV_VALIDATION=1 yarn lint
      - name: Type-checking
        run: yarn type-check
      - name: Testing all files
        run: SKIP_ENV_VALIDATION=1 yarn test
      - name: Testing in CI
        run: yarn test:ci
      - name: Building
        run: yarn build
